# Corn and Soybeans

library(tidyverse)
library(sf)
library(ggplot2)
library(rnaturalearth)
library(rnaturalearthdata)
library(rgeos)
library(tools)
library(maps)
library(stringi)
library(readxl)
library(readr)
library(tm)
library(Ckmeans.1d.dp)
library(grid)
library(gridExtra)
library(rhandsontable)
library(cowplot)
